// <auto-generated />
namespace Pasifika.Business.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Arreglo35 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Arreglo35));
        
        string IMigrationMetadata.Id
        {
            get { return "201502111840222_Arreglo35"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
